# Generated by Django 3.1 on 2022-06-07 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.RenameModel(
            old_name='Season',
            new_name='Material',
        ),
        migrations.RenameField(
            model_name='shoes',
            old_name='season',
            new_name='material',
        ),
        migrations.RemoveField(
            model_name='shoes',
            name='lining_material',
        ),
        migrations.RemoveField(
            model_name='shoes',
            name='sole',
        ),
        migrations.RemoveField(
            model_name='shoes',
            name='upper_material',
        ),
        migrations.AlterField(
            model_name='shoes',
            name='img',
            field=models.ImageField(upload_to='static/images'),
        ),
        migrations.RemoveField(
            model_name='shoes',
            name='the_size',
        ),
        migrations.AddField(
            model_name='shoes',
            name='the_size',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='The_size',
        ),
        migrations.AddField(
            model_name='shoes',
            name='сompound',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.compound'),
            preserve_default=False,
        ),
    ]
