# Generated by Django 3.1 on 2022-06-07 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20220607_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoes',
            name='material',
        ),
        migrations.AddField(
            model_name='shoes',
            name='material',
            field=models.ManyToManyField(to='home.Material'),
        ),
    ]
