# Generated by Django 3.1 on 2022-06-15 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20220615_1709'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
